### ISSUE TITLE
show encrypted email in template AjaxLocationList.html

### ISSUE THREAD

**Issue by martin-git-kristensen** [joachimruhs/myleaflet#10]
In the file AjaxLocationList.html the value {location.email} show the email field from tt_address post in clear text under the map.

I want to use the typo3 viewhelper <f:link.email> so the mail address is shown encrypted as I have the config.spamProtectEmailAddresses = 1 in setup in my maintemplate for my typo3 site.

The problem is when I use: <f:link.email email="{location.email}">email</f:link.email> instead of just {location.email} in AjaxLocationList.html nothing shows up in the search result.

The content of the div id="ajaxResult" is simply empty - why can I not use the <f:link.email> viewhelper here?

**Comment by joachimruhs** [comment]
Hello,
I got this error when using <f:link.email...
Call to a member function getMailTo() on string

In Ajax there is no $GLOBALS['TSFE']->cObj in the EmailViewHelper therefor we got an error.

**Comment by joachimruhs** [comment]
Hello,
it seems to be an issue of the standaloneView rendering the f:link.email tag.
...
