### ISSUE TITLE
routeEnhancers

### ISSUE THREAD

**Issue by themib** [joachimruhs/myleaflet#11]
Hello,
I'm trying to configure a routeEnhancer. Unfortunately no setting works:

routeEnhancers:  
  Myleaflet:
    type: Extbase
    extension: Myleaflet
    plugin: SingleView
    routes:
      - routePath: '/{address_slug}'
        _controller: 'Address::show'
        _arguments:
          address_slug: Address
    aspects:
      address_slug:
        type: PersistedAliasMapper
        tableName: tt_address
        routeFieldName: slug 

Where is the mistake?

**Comment by joachimruhs** [comment]
Hello,

try something like this:

  Myleaflet:
    type: Extbase
    extension: Myleaflet
    plugin: SingleView
    limitToPages:
      - 86
    routes:
      - { routePath: '/show/{address_slug}', _controller: 'Address::show', _arguments: {'address_slug': 'locationUid'} }
    aspects:
      address_slug:
        type: PersistedAliasMapper
        tableName: 'tt_address'
        routeFieldName: 'slug'

**Comment by themib** [comment]
Hello,

...and thank you.
But now if I set the limitation to my "SinglePage" the ajaxRequest doesn't work anymore and in the Dev-Console I get an error: "500 (Internal Server Error)". So now results are loaded.

**Comment by joachimruhs** [comment]
Create an other page for the SingleView only for the AjaxSearch and one page with SingleView for the slugs. This works!

**Comment by joachimruhs** [comment]
Hi,

in config.yaml use

    limitToPages:
      - 86
      - 85

85 is the page with AjaxSearch and 86 the page with SingleView plugin - works as expected.

**Comment by themib** [comment]
Thank you for your feedback and help. Got it going.
