### ISSUE TITLE
AjaxLocationListInfoWindow location.www no real path in link

### ISSUE THREAD

**Issue by asche76** [joachimruhs/myleaflet#12]
Hi,
is it possible to get the full real path link instead of this? t3://page?uid=218 

![leaflet-ajax-loaction](https://user-images.githubusercontent.com/47745128/123783718-f6ca8300-d8d6-11eb-99bd-0d5051a0548d.png)

regards Sascha

**Comment by joachimruhs** [comment]
Hello,
the link is build with fluid <f:link.action action="show"  extensionName="myleaflet" pluginName="SingleView" controller="Address" pageUid="{settings.detailsPageId}"...

Have you set the detailsPageId in the constant editor?

**Comment by joachimruhs** [comment]
Here the link is correct
https://www.web-services-ruhs.de/myleaflet

in the template AjaxLocationListInfoWindow.html

**Comment by asche76** [comment]
hi, 
ok, i do not use or need the single view. i only use the location.www of the tt_address entry to link to some other page inside the T3 system: 

![image](https://user-images.githubusercontent.com/47745128/123791225-7bb99a80-d8df-11eb-95dd-8d74132931ac.png)

![image](https://user-images.githubusercontent.com/47745128/123790859-182f6d00-d8df-11eb-97a3-b3033df8b86b.png)

**Comment by joachimruhs** [comment]
Hi,
{location.www} is your input in field www

Try something like
<f:link.typolink parameter="{location.www}">
   Linktext
</f:link.typolink>

you should use a viewhelper to get a correct link. If the viewhelper did not work because we are in Ajax then insert the url in the field www of the ttaddress record.

**Comment by asche76** [comment]
hi,
sadly <f:link.typolink parameter="{location.www}">www</f:link.typolink> does not work, no address is shown on the map anymore.
then i have to ask a code colleague for more.

very nice thanks for the fast response + best regards

**Comment by joachimruhs** [comment]
Hi,
 try this in one line - note the changed apostrophs - this works...

info += '<div><f:link.typolink parameter="{location.www}"></f:link.typolink></div>';

**Comment by asche76** [comment]
wao, great, it works - 1000 times thanks
best regards
