### ISSUE TITLE
Pins&Radial Search worldwide default

### ISSUE THREAD

**Issue by t-bittner** [joachimruhs/myleaflet#13]
Hello
is there a possibility to set the card so that the set pins (worldwide) are completely displayed?
Currently only the test locations within Germany and 500km are displayed by default.

Also the question of whether you can remove the field for the country selection, so that you search by entering an address on the complete map.

If you have any information on how I could do something like that, I would be grateful.

**Comment by joachimruhs** [comment]
Hi.

you can change the template AjaxSearch.html for your needs (radius etc...).
for example
<option value="25000" selected="selected">25000 km</option>
and hide the select box with css or element style...

Regards

**Comment by joachimruhs** [comment]
Hi,
the field country is used for the startingpoint from which the radial search is done.

The extension gets the coordinates of the city and country from the web.

...

**Comment by t-bittner** [comment]
Hi there,
Thank you for the first input regarding the previous questions.

Due to new customer requirements, I wanted to ask whether it is possible to use the map in such a way that when the user selects a country via the dropdown, only the pins within the country are displayed, even if the radius is 25000km.

With my current test pins within the USA, no pins are given to me when I select the "US" dropdown.

Regards

**Comment by joachimruhs** [comment]
Hi, 
have your addresses US in the country field or somthing like california etc ?
You have to use the extension myttaddressmap and you need a google account.

If you want to search for US then US should the country field.
