### ISSUE TITLE
Search via PostCode and Searchresult Link to the Main Map not to DetailView

### ISSUE THREAD

**Issue by archyart** [joachimruhs/myleaflet#14]

**Comment by archyart** [comment]
Is it possible that i search via city or postcode? Not only city.
Is it possible to link the search rusults item to the Main map marker. That only the one item will zoomed in when i push the link.

**Comment by joachimruhs** [comment]
Hi,

for this you have the constant resultLimit = 300 to limit the results for your desire. May be it would be better to use the extension myttaddressmap and the plugin AjaxSearch. There is an autocompleter for the searchField  implemented....

**Comment by joachimruhs** [comment]
Hi,

for this you have to use extension myttaddressmap and leave the searchfield empty and select only different country. But in this extension you need a google account.

**Comment by archyart** [comment]
Thx
