### ISSUE TITLE
Singletree Project with multiple languages

### ISSUE THREAD

**Issue by t-bittner** [joachimruhs/myleaflet#15]
Hi there,

I currently have the following problem with the multilingualism of the extension.

The map should be displayed for several languages ​​of the website.
For this I overwrite the "constants" for the ResultID as follows:

`[244 in tree.rootLineIds && siteLanguage("locale") == "en_US"]
plugin.tx_myleaflet {
 settings {
resultPageId = 291
}
}
[end]`

The PageUid "244" is the page id of the English language version.
The website is accessed via the same URL and is only displayed with the addition "/en/".

Unfortunately, the map is not loaded. I get the following error in devtools:

POST https://domain.tpl/en/index.php?eIDx=myleaflet&id=60 404

The ID "60" within the error message is the page ID of the main language German.

Strangely, the correct ID's are displayed in the backend via the object browser, but not in the frontend.

Do you have any hints as to what might be causing this?
In addition to adjusting the "constant", does the route hancer also have to be adjusted for a simple display of the map without a detailed view?

Regards

**Comment by joachimruhs** [comment]
Hi,
I could not access domain.tpl...

**Comment by t-bittner** [comment]
The domain is only an example, the project is currently running on a local web server.

**Comment by joachimruhs** [comment]
Hi,
here you can see the map in Deutsch and English.
https://www.web-services-ruhs.de/myleaflet

**Comment by t-bittner** [comment]
This looks like a single tree structure, where the desired behavior works.
Have you also only adjusted the constants relating to the resultPageUid here?

**Comment by joachimruhs** [comment]
No, I use the same page for different languages

**Comment by joachimruhs** [comment]
Hi,

do not use resultPageId, use the detailsPageId

**Comment by t-bittner** [comment]
if I leave the resultui empty and use the detailid instead, I get the same behavior.

**Comment by joachimruhs** [comment]
Try this in condition without locale
[244 in tree.rootLineIds]
...

**Comment by joachimruhs** [comment]
Just test it without any condition in constants

plugin.tx_myleaflet.settings.detailsPageId = 291

**Comment by t-bittner** [comment]
if I test it without conditions, the wrong id is automatically drawn for the default language.

strange behavior is when I set the siteconfig so that the language version is called using a subdomain (lang.domain.tpl), the map works.

Do you have to specially configure the routenhancer for a single-tree implementation with domain.tpl/lang?

**Comment by joachimruhs** [comment]
Hi,
no no routeenhancer for that.

**Comment by joachimruhs** [comment]
It seems your condition is not correct...

**Comment by t-bittner** [comment]
I don't think it's a constant problem as it strangely works with the following url:
http://development.localhost/index.php?eIDx=myleaflet&id=22&L=1

but not with the following URL:
http://development.localhost/en/index.php?eIDx=myleaflet&id=22

for this ajax call I always get the status 404.

**Comment by joachimruhs** [comment]
Hi,

you have the fluid variable {L} in template AjaxSearch.html.
this way you can modify the ajax call
var ajaxRequestUrl = "index.php?eIDx=myleaflet&id=" + id + "&L={L}"

May be this helps
