### ISSUE TITLE
tt_address override typo3 11.5

### ISSUE THREAD

**Issue by martin-git-kristensen** [joachimruhs/myleaflet#16]
It seems like the file: Configuration/TCA/Overrides/tt_address.php is not prepared for typo3 11.5 - the typo3 backend says:
PHP Warning: Undefined array key "Tx_Myleaflet_Address" in /typo3conf/ext/myleaflet/Configuration/TCA/Overrides/tt_address.php line 44

**Comment by joachimruhs** [comment]
Hello,
which version of tt_address?

**Comment by martin-git-kristensen** [comment]
tt_address 6.0.1

**Comment by joachimruhs** [comment]
Hi,
just try to comment line 43 and 44

**Comment by martin-git-kristensen** [comment]
ok - after outcomment line 43 and 44 the error is gone - BUT the frontend of the website is spitting this out:
1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Trying to access array offset on value of type null in /typo3conf/ext/myleaflet/Classes/Middleware/MapUtilities.php line 38 - and then a very long page with errors and no design from the website.

**Comment by joachimruhs** [comment]
Hi,
which php version you use?
What are your settings for [SYS][errorHandlerErrors] and
[SYS][exceptionalErrors]?

May be it is better to use the default settings of this constants.

**Comment by martin-git-kristensen** [comment]
php version 8.0.11 
[SYS][errorHandlerErrors] = 30466
Current PHP error code 30466 represents:
E_WARNING | E_USER_ERROR | E_USER_WARNING | E_USER_NOTICE | E_RECOVERABLE_ERROR | E_DEPRECATED | E_USER_DEPRECATED

I guess these values are the default - I have not made changes to them.


[SYS][exceptionalErrors] = 12290
Current PHP error code 12290 represents:
E_WARNING | E_RECOVERABLE_ERROR | E_DEPRECATED

**Comment by joachimruhs** [comment]
Ok,
I have the same constants. Can you just try to use a lower php version?

**Comment by martin-git-kristensen** [comment]
That is unfortunately not possible for me - I have a rented server with 3 different virtuel configurationS - and the php version is not a parameter I can toggle.
But I can try to move the whole website to the other server - with php 7.4.25
I use composer so it should be quite easy.

**Comment by joachimruhs** [comment]
Hi,
I tested with php 8.0.16 and got many errors and warnings...
I switched back to php 7.4.28 and everything  is fine.

**Comment by joachimruhs** [comment]
Do you use plesk as server configuration tool?

**Comment by martin-git-kristensen** [comment]
ok - it could be very nice if the extension could go with php 8...
I have a server conf tool but I cant mess with the php version.

**Comment by joachimruhs** [comment]
I just tried php 8.0.16.
But then the TYPO3 Backend did not work too.

**Comment by joachimruhs** [comment]
I just tried php 8.0.16
and [SYS][exceptionalErrors] = 4096 

then the frontend works, in bachend I got some warnings but seems to work...
Set the debug preset to live the the warnings are gone.

**Comment by martin-git-kristensen** [comment]
hello - actually it was a big help - it seems like the errors disappeared both on the backend and frontend :-)

**Comment by martin-git-kristensen** [comment]
Where do I set the zoomfactor on the map - when using the tt_address show map plugin

**Comment by martin-git-kristensen** [comment]
ok - got the zoomfactor in Leaflet.js in tt_address public folder
