### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by anderlk** [joachimruhs/myleaflet#17]
How is it possible to set the initialMapCoordinates for the backend Marker?

**Comment by joachimruhs** [comment]
Hi,
in the constant editor you can set **initialMapCoordintes**
default is latitude,longitude **48,8**

Regards

**Comment by anderlk** [comment]
Thanks for your request.

Works this lat/lon selection for Backend, too?

**Comment by joachimruhs** [comment]
What do you mean with Backend?
In the Backend you have no map.

**Comment by anderlk** [comment]
This View: The Coardinates from the Selection in Backend  ![Bildschirmfoto 2022-07-11 um 17 23 10](https://user-images.githubusercontent.com/12695520/178299440-55ffbad1-966c-4cfc-ba4b-394120d3c078.png)

**Comment by joachimruhs** [comment]
Ok, I see.
Just enter a second address record with other coordinates - then the map is zoomed to display all markers...

**Comment by joachimruhs** [comment]
Hi,
now I understand - that is the coordinate wizard from tt_address.
At the left top corner you have a button to "Import marker-coordinates"

Because this is no issue of myleaflet I close this issue.
