### ISSUE TITLE
Integration: Set markericon size

### ISSUE THREAD

**Issue by anderlk** [joachimruhs/myleaflet#18]
At the moment, there is no possibility to set marker icon size. Is it possible to implement a configuration of icon size for example via TypoScript?

Regards, Andreas

**Comment by joachimruhs** [comment]
Ok,
I will implement markerIconWidth and markerIconHeight in the constants.

**Comment by joachimruhs** [comment]
New version 1.3.1

**Comment by anderlk** [comment]
Hi @joachimruhs,i need the function, because I would like to use my own markericons, which have different dimensions. Currently, I have manually adjusted the size in the PHP file, but this is not useful, because I can therefore no longer easily update without constantly re-adjusting the adjustments.

Thank you very much. Integration in constants is great. I think I am not the only one who will need this feature. Since there are now very many different markericons in different sizes.

Regards Andreas
![Bildschirmfoto 2022-07-16 um 14 05 34](https://user-images.githubusercontent.com/12695520/179354298-3bba10d7-b6bb-494c-bbac-f970a23da0e5.png)
)

**Comment by anderlk** [comment]
Thanks for the quick implementation, works perfect!!
