### ISSUE TITLE
integrating Leaflet.markercluster

### ISSUE THREAD

**Issue by danielpesel** [joachimruhs/myleaflet#2]
Hi,

i like what you are doing with myleaflet.

my question is it posible to integrate Leaflet.markercluster https://github.com/Leaflet/Leaflet.markercluster ? 

i tryed it my self but i am not so good in coding

Thanks anyways

**Comment by joachimruhs** [comment]
I will have a look on that in the next days…

Regards

**Comment by joachimruhs** [comment]
Hello Mr. Pesel,

please test the attached Version.

Regards
[myleaflet_0.6.8_201912300626.zip](https://github.com/joachimruhs/myleaflet/files/4009033/myleaflet_0.6.8_201912300626.zip)

**Comment by danielpesel** [comment]
Hello,

so i tested it and get a error:

in Typo3:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: An exception
occurred while executing 'SELECT distinct a.*, (acos(sin(0.88904211501947)
* sin(latitude * 0.017453292519943) + cos(0.88904211501947) * cos(latitude
* 0.017453292519943) * cos((6.959974 - longitude) * 0.017453292519943))) *
6370 as `distance`, (SELECT GROUP_CONCAT(e.title ORDER BY e.title SEPARATOR
', ') from tt_address d, sys_category e, sys_category_record_mm f where
f.uid_local = e.uid AND f.uid_foreign= d.uid and d.uid = a.uid and e.pid in
() ) as categories FROM `tt_address` `a` WHERE (`a`.`pid` IN (NULL)) AND
((`a`.`deleted` = 0) AND (`a`.`hidden` = 0)) HAVING `distance` <= ? ORDER
BY `distance` ASC LIMIT 1000' with params [500]: You have an error in your
SQL syntax; check the manual that corresponds to your MariaDB server
version for the right syntax to use near ') ) as categories FROM
`tt_address` `a` WHERE (`a`.`pid` IN (NULL)) ' at line 9 |
Doctrine\DBAL\Exception\SyntaxErrorException thrown in file /var/www/vhosts/
pluspunktleben.de/gego.pluspunktleben.de/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
in line 79. Requested URL:
https://gego.pluspunktleben.de/index.php?eIDx=myleaflet&id=4

in the Browser:
ReferenceError: $ is not defined
<anonym> https://gego.pluspunktleben.de/index.php?id=4:335
$(document).ready(function () {

ReferenceError: $ is not defined
<anonym> https://gego.pluspunktleben.de/index.php?id=4:408
$(document).ready(function(){


thank you so much and hopfully my information helps you!

Greetings

*__________________________________*

Absender:

*Daniel Pesel*

Pastor



*Gemeinde Gottes PlusPunkt Leben*

Winterbacher Straße 41, 73614 Schorndorf-Weiler

Tel.: (0 71 81) 66 91 222 • www.pluspunktleben.com •
pastor@pluspunktleben.com


Diese E-Mail kann vertrauliche und/oder rechtlich geschützte Informationen
enthalten. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail
irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und
vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte
Weitergabe dieser Mail ist nicht gestattet.     //     This e-mail may
contain confidential and/or privileged information. If you not the intended
recipient (or have received this e-mail in Error) please notify the sender
immediately and destroy this e-mail. Any unauthorised copying, disclosure
or distribution of the material in this e-mail is strictly forbidden.


Am Mo., 30. Dez. 2019 um 06:34 Uhr schrieb joachimruhs <
notifications@github.com>:

**Comment by joachimruhs** [comment]
First,
you have to set the storagePid in the constant Editor to the page where the data records are located.
Second, you have to include jQuery at the top of the page - can be done with the constant Editor too.

...
