### ISSUE TITLE
Wrong namespace in AddSlashesViewHelper

### ISSUE THREAD

**Issue by sterborg** [joachimruhs/myleaflet#21]
The class `AddSlashesViewHelper` uses

`namespace WSR\Myttaddressmap\ViewHelpers;`

instead of

`namespace WSR\Myleaflet\ViewHelpers;`

I´m getting an error on composer update:

`[ Symfony\Component\DependencyInjection\Exception\InvalidArgumentException ]
  Expected to find class "WSR\Myleaflet\ViewHelpers\AddSlashesViewHelper" in file "/var/www/html/public/typo3conf/ext/myleaflet/Cl
  asses/ViewHelpers/AddSlashesViewHelper.php" while importing services from resource "../Classes/*", but it was not found! Check t
  he namespace prefix used with the resource.`

Also other occurrences of `myttaddressmap` in the code. For example: `tx_myttaddressmap_domain_model_address`

TYPO3 11.5.21
myleaflet 1.3.1, 1.5.10, 1.6.0

**Comment by joachimruhs** [comment]
Hi,
I just delete ths AddSlashesViewHelper and also occurrances of myttaddressmap in the sources. Hope I got all.
I released version 1.6.1
