### ISSUE TITLE
Is myleaflet ready for TYPO3 V12?

### ISSUE THREAD

**Issue by archyart** [joachimruhs/myleaflet#22]
Hello, is the extension ready to use in TYPO3 V12? I get a 500 error when calling /index.php?eIDx=myleaflet&id=2

error:
ViewHelper f:link.action can be used only in extbase context and needs a request implementing extbase RequestInterface.

typo3conf/ext/myleaflet/Classes/Controller/AjaxController.php line 454
$out .= $this->renderFluidTemplate('AjaxLocationListInfoWindow.html', array('location' => $locations[$i], 'categories' => $categories, 'i' => $i,'startingPoint' => $latLon, 'settings' => $this->settings));

/typo3conf/ext/myleaflet/Classes/Controller/AjaxController.php line 503
return $view->render();

/typo3conf/ext/myleaflet/Classes/Middleware/MapUtilities.php line 51
$out = $ajaxController->indexAction($request, $response);

/typo3conf/ext/myleaflet/Classes/Controller/AjaxController.php line 172
$response = $this->processPostRequest($request, $response);

/typo3conf/ext/myleaflet/Classes/Controller/AjaxController.php line 381
$out .= $this->getMarkerJS($locations, $categories, $latLon, $this->_GP['radius']);

Greetings

**Comment by joachimruhs** [comment]
Hi,
did you use the templates which come with the extension?

**Comment by archyart** [comment]
No,sorry...
but i used them now and become this failure:
PHP Warning: Undefined variable $arr in /www/htdocs/w01151b7/2023v12.freundeskreise-saar.de/typo3conf/ext/myleaflet/Classes/Controller/AddressController.php line 214
Greetings

**Comment by archyart** [comment]
No sorry, after implementating the new templates it works. soooory. the night was too long i think;-)

**Comment by joachimruhs** [comment]
Hi,
insert some sys_categories first!
