### ISSUE TITLE
Typo3 V12 Route Enhancer doesn't work

### ISSUE THREAD

**Issue by archyart** [joachimruhs/myleaflet#23]
Hello,
the routing doesn't work. 
config.yaml
  Myleaflet:
    type: Extbase
    extension: Myleaflet
    plugin: SingleView
    limitToPages:
    - 2
    - 9
    routes:
      -
        routePath: '/show/{company}'
        _controller: 'Address::show'
        _arguments:
          company: 'locationUid'
    aspects:
        company:
            type: PersistedAliasMapper
            tableName: tt_address
            routeFieldName: company

?id=9&tx_myleaflet_singleview[action]=show&tx_myleaflet_singleview[locationUid]=421

In TYPO3 V11 it works...

What is the issue?

Greetings

**Comment by joachimruhs** [comment]
Hi,
it seems that this is not an issue of myleafet. It is an issue of your route enhanccer or may be in TYPO3 12  they have changed something in the enhancers.
I have not worked now with enhancers in TYPO3 12.
Regards

**Comment by archyart** [comment]
do you tested the route enhancers now? TYPO3 12 LTS is out right now... 
Greetings

**Comment by joachimruhs** [comment]
Not yet tested, I work on other problems with TYPO3 12 LTS...

**Comment by archyart** [comment]
If you have a solution please write... good luck for your problems...

**Comment by joachimruhs** [comment]
Hi,
the AjaxLocationList is not in Extbase context, therefor the viewhelper f:link does not work anymore. You can use the extension myttaddressmap but here you **should not use**  the Ajaxsearch plugin.

**Comment by archyart** [comment]
thx for the quick information. the customer don't want use google maps and needs the ajaxsearch...
greetings
