### ISSUE TITLE
Failure: Geocoding Error: NOT FOUND

### ISSUE THREAD

**Issue by archyart** [joachimruhs/myleaflet#26]
Since this morning is this failure "Geocoding Error: NOT FOUND" what could be the reason?

**Comment by archyart** [comment]
https://nominatim.openstreetmap.org/search/ that has to change in AjaxController in Line 133

**Comment by joachimruhs** [comment]
I just create a new version myleaflet-1.7.1.
Can you test it?

**Comment by archyart** [comment]
yes but first at 15:00. 
i write back

**Comment by archyart** [comment]
its working with TYPO3 V11 and V12. Greetings
