### ISSUE TITLE
Ext is not TYPO3 11 compatible

### ISSUE THREAD

**Issue by froemken** [joachimruhs/myleaflet#28]
Hello,

setRequest was added with TYPO3 12. So this will fail on TYPO3 11:

https://github.com/joachimruhs/myleaflet/blob/master/Classes/Controller/AjaxController.php#L484

See FB post:
https://www.facebook.com/groups/250938618364487/permalink/5423090801149217/

Nice greetings

Stefan

**Comment by joachimruhs** [comment]
Hi,

fixed with version 1.8.6. 

Thx for reporting!
