### ISSUE TITLE
Wrong icon in single view

### ISSUE THREAD

**Issue by spooodesign** [joachimruhs/myleaflet#29]
In the "AjaxLocationList.html" custom map-icons are shown correctly. But in "Show.html" these custom map-icons are not shown in the current version.

**Comment by joachimruhs** [comment]
Hi,
that's correct - the default icon is shown.
May be in later version I'll fix that.

**Comment by joachimruhs** [comment]
Version 1.8.7 fixed the issue! Template Show.html changed.

**Comment by spooodesign** [comment]
Thanks a lot, works like a charm! I really appreciate it. 
Maybe you could think of using the markerIconWidth and markerIconHeight also in the single-view that are defined in the constants. This would help developers to keep it streamlined.

**Comment by joachimruhs** [comment]
Hi,
the template Show.html has changed which uses the defined constants!

**Comment by spooodesign** [comment]
Hello, 
thanks. I replaced Show.html but now the marker is not shown anymore in the single view ...

**Comment by joachimruhs** [comment]
Hi,
extension works fine https://www.joachim-ruhs.de/extensions/myleaflet/ajaxsearch
... that was TYPO3 12

and TYPO3 11
https://www.web-services-ruhs.de/myleaflet/ajaxsearch
works too

**Comment by spooodesign** [comment]
Did you try it with a custom map-icon? I tried it several times and it does not work ... (TYPO3 11)

**Comment by joachimruhs** [comment]
Hi,
just tested with custom mapIcon - works in TYPO3 11.
The icons should have dimension 12 x 20 or similad for best results.

**Comment by joachimruhs** [comment]
Hi,
in Show.html I fixed a bug:

          var mapIcon = L.icon({
				iconUrl: "/fileadmin/ext/myleaflet/Resources/Public/MapIcons/" + icon,
				iconSize:     [  <f:format.raw>{settings.markerIconWidth} , {settings.markerIconHeight}</f:format.raw>], // size of the icon
				iconAnchor:   [  <f:format.raw>{settings.markerIconWidth} / 2 , {settings.markerIconHeight}</f:format.raw>]
			});

**Comment by spooodesign** [comment]
Super, thanks a lot, now it works like a charm! I was close to your solution but you were faster. (-:
