### ISSUE TITLE
htmlspecialchars() creates problems with the rendering

### ISSUE THREAD

**Issue by danielpesel** [joachimruhs/myleaflet#3]
Hi,
in the rendering of the discription the html code is showing in the frontend.
when the htmlspecialchars() is remove everything works fine.
is this code important?
https://github.com/joachimruhs/myleaflet/blob/94746fdde2445a5262e3ba388fc854a0b60c2516/Classes/Controller/AjaxController.php#L354

**Comment by joachimruhs** [comment]
Hi,

may be you can run into XSS issues without htmlspecialchars.
Otherwise you can use $locations[$i]['infoWindowDescription']
...

**Comment by joachimruhs** [comment]
Ok, fixed. Changed the sequence of desciption and infoWindowDescription in AjaxController.

**Comment by danielpesel** [comment]
thanks!!

It works now
