### ISSUE TITLE
Categories in the same format in list- and singele-view

### ISSUE THREAD

**Issue by spooodesign** [joachimruhs/myleaflet#30]
In the list-view the categories are shown as comma separated text. In contrast to this the categories in the single vie are shown as array what is much better. F.e. if you would like to style each category as a badge or button then you need an array. And if the category array also would contain the category id a link to all addresses in the category could be created.

**Comment by joachimruhs** [comment]
Hi,
it is not planned to implement this because the comma separated list came from one sql statement.
To get an array of categories of the location would slow the extension especially when there are hundreds of locations and for each location you have a sql function call.
