### ISSUE TITLE
JS Error: POST index.php?id=17 500 (Internal Server Error) on Typo3 12

### ISSUE THREAD

**Issue by p-view** [joachimruhs/myleaflet#31]
Hi, is some setup to Ajax work?

**Comment by joachimruhs** [comment]
See documentation/AdministratorManual
https://github.com/joachimruhs/myleaflet/blob/master/Documentation/AdministratorManual/Index.rst

Make sure you have installed jQuery on *top* of the page

You can use the jQuery from myleaflet - see constant editor.

**Comment by p-view** [comment]
jquery is on top and i see also the map. storagePid is set. I think tha ajax response is wrong. Need the call any type?

**Comment by joachimruhs** [comment]
No.
Have you inserted some categories?
Can you give me the URL?

**Comment by p-view** [comment]
Have found my Problem. Was a missing "/"  ajaxRequestUrl. Sorry for your time waste ;) THX
