### ISSUE TITLE
T3 11 (1.8.8) add new address - backend map don't show correct coordinates

### ISSUE THREAD

**Issue by asche76** [joachimruhs/myleaflet#32]
if you add a new address with street, zip-code in earlier version the map shows instant the correct coordinates of the new address on the map.
now it shows only copenhagen.
so you have to get the coordinates via browser google maps and add them by hand in the new address entry.
this behaviour is since an update to 1.8.8 from a version of 2022.

![image](https://github.com/joachimruhs/myleaflet/assets/47745128/638ba82c-2701-4237-b755-d8411e2e1f62)

**Comment by joachimruhs** [comment]
Hi,
that is not an issue of myleaflet.
It is from ttaddress. You can get the coordinates here
![image](https://github.com/joachimruhs/myleaflet/assets/51224372/98a7d115-7944-4ccc-88c0-c5a1fe9e4770)

There is a fix in tt_address
https://github.com/FriendsOfTYPO3/tt_address/commit/b96f2c46daa505ff423a025cb1867785af4b9b54

**Comment by asche76** [comment]
awesome big thx
