### ISSUE TITLE
Overwriting Templates isn't working as expected

### ISSUE THREAD

**Issue by taunusweb** [joachimruhs/myleaflet#6]
Hi, overwriting Templates in the Constant Editor isn't working, the same Information in my own TS Setup is working: but not for all Files:
```
plugin.tx_myleaflet {
    view {
        templateRootPaths.1 = EXT:my_sitepackage/Resources/Private/Extensions/myleaflet/Templates/
        partialRootPaths.1 = EXT:my_sitepackage/Resources/Private/Extensions/myleaflet/Partials/
        layoutRootPaths.1 = EXT:my_sitepackage/Resources/Private/Extensions/myleaflet/Layouts/
    }

}
```
is working, for e.g. "AjaxSearch.html" but not for "AjaxLocationListInfoWindow.html"

The same Paths in the Constant Editor doesn't work at all, but in the TSOB, everything seems correct. 
I'm using Version 0.8.1 with TYPO3 10LTS

**Comment by joachimruhs** [comment]
Hello,
I tested it and it is working even the AjaxLocationListInfoWindow (this is a javascript part...).
See https://www.web-services-ruhs.de/myleaflet.

**Comment by taunusweb** [comment]
Sorry, I've forgot, that I had an own Template for that Site... Everything is fine, I definitly need some holidays ;) You can delete the whole Issue, if you want.
