### ISSUE TITLE
"Geocoding Error: NOT FOUND" when using radial search with a space charakter

### ISSUE THREAD

**Issue by taunusweb** [joachimruhs/myleaflet#7]
I search e.g. for "Bad Homburg", then I get the Error, if I do the same with "Bad-Homburg", everything is fine.
Thanks Uli

**Comment by joachimruhs** [comment]
Hello,

that's an issue of https://nominatim.openstreetmap.org not of myleaflet!
The Google geocoder at https://www.web-services-ruhs.de/myttaddress works fine with the Ext myttaddressmap.

Regards

   Joachim Ruhs

**Comment by taunusweb** [comment]
Ah, thanks, my Customer doesn't want any Google Service on the Site, but I can provide an explanation, how to use the search, that will fit my needs.
