### ISSUE TITLE
Map stopped working

### ISSUE THREAD

**Issue by SBWebdev** [joachimruhs/myleaflet#8]
Hello,

on a customer website with Typo3 9.5.4, myleaflet 0.4 and tt_address 4.3.0, the map stopped working. It was noticed after a PHP update from 7.2.x to 7.3 but it the problem could have existed before. 

In the developer console I see the following error messages:
`Uncaught SyntaxError: missing variable name pagename:295:16 (in GeocodeByClient function definition)
Uncaught ReferenceError: group is not defined
    resizeMap https://www.domainname.com/category/pagename:364
    <anonymous> https://www.domainname.com/category/pagename:374
pagename:364:7
Uncaught ReferenceError: group is not defined
    resizeMap pagename:364
    jQuery 2
pagename:364:7
`

I have not changed any configurations and the map worked before. Even if you don't want to create a bug fix because it's an older version, I'd be grateful for some hints/advice how to fix it myself because I couldn't find a solution even though I looked through the code for hours.

**Comment by joachimruhs** [comment]
Hello,
can I access the page? Url?
...

**Comment by joachimruhs** [comment]
Hi,
please check if this is in your HTML code

var map = '';
	var marker = [];
	var group = '';
	var markerArray = [];

...

**Comment by joachimruhs** [comment]
Hi,
the errors you described are javascript errors.
Pls compare your template AjaxSearch.html with the original template.

Regards
   ...
