### ISSUE TITLE
sys_categories

### ISSUE THREAD

**Issue by martin-git-kristensen** [joachimruhs/myleaflet#9]
In the current version sys_categories is only shown on the AjaxMap page if the sys_categories are located in the "Data" sysfolder where also the tt_address posts are located.
Is it possible to read the sys_categories regardless which pid in the pagetree they are located in?

**Comment by joachimruhs** [comment]
Hello,

no, that is at the moment not possible. If I read all sys_categories there will be categories which belongs to other extensions...

Regards

  Joachim Ruhs

**Comment by martin-git-kristensen** [comment]
ok - is it then possible to make a category pid in the constant editor like the other constants settings. It could be nice to be able to determine which pid the syscategories are read from?
Regards 
Martin Kristensen

**Comment by joachimruhs** [comment]
Hi,
the sys_categories are read from "Default storage PID" in the constant editor!
